version: "3.8"

services:
  gateway:
    image: nginx:1.25-bookworm
    restart: always
    volumes:
      - ./gateway_nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "5000:80"
    depends_on:
      - order-web
      - stock-web
      - user-web

  redis-master:
    image: redis:8.6
    command: redis-server --requirepass redis --masterauth redis

  redis-replica-1:
    image: redis:8.6
    command: redis-server --replicaof redis-master 6379 --requirepass redis --masterauth redis
    depends_on:
      - redis-master

  redis-replica-2:
    image: redis:8.6
    command: redis-server --replicaof redis-master 6379 --requirepass redis --masterauth redis
    depends_on:
      - redis-master

  order-web:
    build: ./order
    deploy:
      replicas: 10

  order-worker:
    build: ./order
    deploy:
      replicas: 8

  stock-web:
    build: ./stock
    deploy:
      replicas: 3

  stock-worker:
    build: ./stock
    deploy:
      replicas: 6

  user-web:
    build: ./payment
    deploy:
      replicas: 3

  user-worker:
    build: ./payment
    deploy:
      replicas: 6