worker_rlimit_nofile 65536;

events {
    worker_connections 16384;
}

http {
    upstream order-backend {
        server order-web:5000;
        keepalive 256;
    }

    upstream stock-backend {
        server stock-web:5000;
        keepalive 256;
    }

    upstream payment-backend {
        server user-web:5000;
        keepalive 256;
    }

    server {
        listen 80;

        location /orders/ {
            proxy_pass http://order-backend/;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
        }

        location /stock/ {
            proxy_pass http://stock-backend/;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
        }

        location /payment/ {
            proxy_pass http://payment-backend/;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
        }
    }
}