sentinel monitor order-master redis-order 6379 2
sentinel down-after-milliseconds order-master 5000
sentinel failover-timeout order-master 10000
sentinel parallel-syncs order-master 1
sentinel auth-pass order-master redis

sentinel monitor stock-master redis-stock 6379 2
sentinel down-after-milliseconds stock-master 5000
sentinel failover-timeout stock-master 10000
sentinel parallel-syncs stock-master 1
sentinel auth-pass stock-master redis

sentinel monitor payment-master redis-payment 6379 2
sentinel down-after-milliseconds payment-master 5000
sentinel failover-timeout payment-master 10000
sentinel parallel-syncs payment-master 1
sentinel auth-pass payment-master redis

sentinel monitor orchestrator-master redis-orchestrator 6379 2
sentinel down-after-milliseconds orchestrator-master 5000
sentinel failover-timeout orchestrator-master 10000
sentinel parallel-syncs orchestrator-master 1
sentinel auth-pass orchestrator-master redis

requirepass redis