auth:
  password: redis

sentinel:
  enabled: true
  masterSet: mymaster
  quorum: 2
  resources:
    requests:
      memory: 128Mi
      cpu: 100m

master:
  persistence:
    enabled: true
    size: 4Gi
  resources:
    requests:
      memory: 512Mi
      cpu: 250m

replica:
  replicaCount: 3
  persistence:
    enabled: true
    size: 4Gi
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
